import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "STYLO | Life Style",
  description: "Generated by Stylo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
