import type { Metadata } from "next";
import "../globals.css";

import Navbar from "@/components/home/Navber";
import Label from "@/components/home/Label";
import Footer from "@/components/home/Footer/FooterOne";
import FooterTwo from "@/components/home/Footer/FooterTwo";

export const metadata: Metadata = {
  title: "STYLO.FIT® LIFE STYLE | Shop Raw Baggy for Men & Women",
  description: "Generated by Stylo.fit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <Label />

        {children}

        <Footer></Footer>
        <FooterTwo></FooterTwo>
      </body>
    </html>
  );
}
