import type { Metadata } from "next";
import "../styles/globals.css";

import Navbar from "@/components/home/Navber";

export const metadata: Metadata = {
  title: "STYLO | Life Style",
  description: "Generated by Stylo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
